version: '3.8'
services:
# rp:
#     image: nginx:stable-alpine
#     container_name: readstore_nginx_rp
#     ports:
#       - "80:80"
#     volumes:
#       - ./rp/default.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: readledger_pg
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=test
      # - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
    #anonymous volumes fail on windows
      - pgvolume:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin:
    container_name: readledger_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.ru"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
    #anonymous volumes fail on windows
      - pgadminvolume:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
volumes:
  pgvolume:
    driver: local
  pgadminvolume:
    driver: local