POST http://localhost:8080/resources/findAll HTTP/1.1
content-type: application/json

###
POST http://localhost:8080/resources/findByIds HTTP/1.1
content-type: application/json

{
    "ids": ["d63407ab-a39b-4b76-a676-7c6143a5b35e", "952850d3-aae1-4671-b970-3f5efc647939"]
}

###
POST http://localhost:8080/resources/add HTTP/1.1
content-type: application/json

{
    
    "resourceLabel": "new label",
    "description": "new description"
}


###
DELETE http://localhost:8080/resources/5bd66088-f942-4833-bf3a-3dfe3a9f88c1 HTTP/1.1

###
PUT http://localhost:8080/resources/update HTTP/1.1
content-type: application/json

{
    
    "description": "UPDATED description"
}
