### findAll
POST http://localhost:8080/books/findAll HTTP/1.1
content-type: application/json

### add
POST http://localhost:8080/books/add HTTP/1.1
content-type: application/json

{

  "title": "Book 11",
  "authors": ["64d0062d-9274-4e89-86d3-913defaee6a7"],
  "status": "DONE"
}


### delete
DELETE http://localhost:8080/books/29123f28-a619-4782-991f-f8899f2b8645 HTTP/1.1

### update
POST http://localhost:8080/books/update HTTP/1.1
content-type: application/json

{
  "id": "328e509b-02de-4e6f-b077-dce8c26b28ee",
  "status": "DROPPED"
}
