### findAll
POST http://localhost:8080/comments-book/findAll HTTP/1.1
content-type: application/json


### add
POST http://localhost:8080/comments-book/add HTTP/1.1
content-type: application/json

{
  "comment": "comment 1 to book 1",
  "book": "b5f9c9da-ba42-4748-9c4c-d9c1263f80bc"
}

### findBySeries
POST http://localhost:8080/comments-book/findBySeries HTTP/1.1
content-type: application/json

{
  "ids": ["559cfd59-d917-4d3a-9d25-69b89424968f"]
}

### update
POST http://localhost:8080/comments-book/update HTTP/1.1
content-type: application/json

{
  "id": "17e98420-2b84-4ab4-827c-4d4a36377232",
  "content": "new content"
}

### delete
DELETE  http://localhost:8080/comments-book/9b54b007-239b-4fcb-ad93-25e79fa8d75d HTTP/1.1

